import type { Investigation } from "@/lib/types";

export const investigations: Investigation[] = [
  // ─── Margaret Chen (10231) ───────────────────────────────────────────────────
  {
    id: "inv-004",
    patientId: "10231",
    date: "2024-02-08",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "HbA1c, fasting glucose, fasting lipid panel, CMP",
    status: "completed",
    orderedBy: "Chen, James",
    notes:
      "HbA1c 7.8%. LDL 2.4 mmol/L (on target with statin). eGFR 62 mL/min/1.73m² (mildly reduced — monitor). Fasting glucose 9.1 mmol/L.",
    statusHistory: [
      { status: "pending", date: "2024-02-08", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-02-09", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2024-02-10", updatedBy: "LifeLabs System" },
    ],
    attachedFiles: ["file-003"],
  },
  {
    id: "inv-005",
    patientId: "10231",
    date: "2024-08-15",
    type: "referral",
    source: "Other",
    description: "Referral — ophthalmology for diabetic eye exam",
    status: "in-progress",
    orderedBy: "Chen, James",
    referringPhysician: "Chen, James",
    notes: "Annual diabetic retinopathy screening. Patient overdue by 18 months.",
    statusHistory: [
      { status: "pending", date: "2024-08-15", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-08-20", updatedBy: "Ophthalmology Clinic" },
    ],
  },
  {
    id: "inv-006",
    patientId: "10231",
    date: "2024-08-15",
    type: "referral",
    source: "Other",
    description: "Referral — podiatry for diabetic foot assessment",
    status: "pending",
    orderedBy: "Chen, James",
    referringPhysician: "Chen, James",
    notes: "Annual diabetic foot care referral. Monofilament sensation testing abnormal at last visit.",
    statusHistory: [
      { status: "pending", date: "2024-08-15", updatedBy: "Chen, James" },
    ],
  },
  {
    id: "inv-007",
    patientId: "10231",
    date: "2023-10-12",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "HbA1c and CMP",
    status: "completed",
    orderedBy: "Chen, James",
    notes: "HbA1c 7.5% (improved from 8.1%). eGFR 65. Electrolytes normal on Lisinopril.",
    statusHistory: [
      { status: "pending", date: "2023-10-12", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2023-10-13", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2023-10-14", updatedBy: "LifeLabs System" },
    ],
    attachedFiles: ["file-004"],
  },

  // ─── Raj Patel (33591) ───────────────────────────────────────────────────────
  {
    id: "inv-008",
    patientId: "33591",
    date: "2023-08-14",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "TSH, CBC, CMP — baseline workup to exclude organic cause of depression",
    status: "completed",
    orderedBy: "Wu, Bella",
    notes:
      "TSH 2.1 mIU/L (normal). CBC unremarkable. LFTs normal — safe to initiate Sertraline. Vitamin D 42 nmol/L (mildly low).",
    statusHistory: [
      { status: "pending", date: "2023-08-14", updatedBy: "Wu, Bella" },
      { status: "in-progress", date: "2023-08-15", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2023-08-16", updatedBy: "LifeLabs System" },
    ],
    attachedFiles: ["file-005"],
  },
  {
    id: "inv-009",
    patientId: "33591",
    date: "2024-06-18",
    type: "referral",
    source: "Other",
    description: "Referral — gastroenterology for GERD with failed dietary management",
    status: "in-progress",
    orderedBy: "Wu, Bella",
    referringPhysician: "Wu, Bella",
    notes: "Symptoms recurred despite lifestyle modification. Referral to GI for consideration of upper endoscopy.",
    statusHistory: [
      { status: "pending", date: "2024-06-18", updatedBy: "Wu, Bella" },
      { status: "in-progress", date: "2024-06-25", updatedBy: "GI Clinic Booking" },
    ],
  },
  {
    id: "inv-010",
    patientId: "33591",
    date: "2024-03-05",
    type: "misc",
    source: "Other",
    description: "PHQ-9 standardized depression screening",
    status: "completed",
    orderedBy: "Wu, Bella",
    notes: "PHQ-9 score = 9 at visit (down from 17 at baseline). Clinically significant improvement documented.",
    statusHistory: [
      { status: "pending", date: "2024-03-05", updatedBy: "Wu, Bella" },
      { status: "completed", date: "2024-03-05", updatedBy: "Wu, Bella" },
    ],
  },

  // ─── Sophie Dubois (57720) ───────────────────────────────────────────────────
  {
    id: "inv-011",
    patientId: "57720",
    date: "2023-09-06",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "Serum tryptase, CBC, IgE — post-anaphylaxis workup",
    status: "completed",
    orderedBy: "ER Staff",
    notes:
      "Tryptase 14 ng/mL (elevated at time of reaction, confirming anaphylaxis). Total IgE 420 IU/mL (high). CBC: eosinophilia.",
    statusHistory: [
      { status: "pending", date: "2023-09-05", updatedBy: "ER Staff" },
      { status: "in-progress", date: "2023-09-06", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2023-09-07", updatedBy: "LifeLabs System" },
    ],
    attachedFiles: ["file-007"],
  },
  {
    id: "inv-012",
    patientId: "57720",
    date: "2024-07-30",
    type: "referral",
    source: "Other",
    description: "Referral — allergist for tree nut desensitization immunotherapy assessment",
    status: "pending",
    orderedBy: "Wu, Bella",
    referringPhysician: "Wu, Bella",
    notes: "Patient and family interested in OIT (oral immunotherapy). Referred to Dr. M. Ng, allergist, Edmonton.",
    statusHistory: [
      { status: "pending", date: "2024-07-30", updatedBy: "Wu, Bella" },
    ],
  },
  {
    id: "inv-013",
    patientId: "57720",
    date: "2024-04-11",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "Skin swab — rule out secondary Staphylococcal infection in eczema flare",
    status: "completed",
    orderedBy: "Wu, Bella",
    notes: "No bacterial growth. MRSA screen negative.",
    statusHistory: [
      { status: "pending", date: "2024-04-11", updatedBy: "Wu, Bella" },
      { status: "in-progress", date: "2024-04-12", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2024-04-14", updatedBy: "LifeLabs System" },
    ],
  },

  // ─── Gerald Morrison (68103) ─────────────────────────────────────────────────
  {
    id: "inv-014",
    patientId: "68103",
    date: "2024-01-22",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "INR, CMP, BNP, HbA1c — heart failure and CKD panel",
    status: "completed",
    orderedBy: "Chen, James",
    notes:
      "INR 2.4 (therapeutic). Creatinine 168 umol/L, eGFR 38 mL/min/1.73m² (CKD stage 3b). BNP 420 pg/mL (elevated, consistent with decompensation). HbA1c 8.2% (above target).",
    statusHistory: [
      { status: "pending", date: "2024-01-22", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-01-23", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2024-01-24", updatedBy: "LifeLabs System" },
    ],
    attachedFiles: ["file-009"],
  },
  {
    id: "inv-015",
    patientId: "68103",
    date: "2024-04-03",
    type: "cardiology",
    source: "Cardiology",
    description: "Transthoracic echocardiogram — LVEF assessment",
    status: "completed",
    orderedBy: "Cardiology — Dr. R. Kapoor",
    notes:
      "LVEF 38% (mildly reduced, stable vs prior). Global hypokinesis. No new wall motion abnormalities. Mild mitral regurgitation. Left atrium mildly dilated consistent with AFib.",
    statusHistory: [
      { status: "pending", date: "2024-03-20", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-04-01", updatedBy: "Cardiology Clinic" },
      { status: "completed", date: "2024-04-03", updatedBy: "Cardiology — Dr. R. Kapoor" },
    ],
    attachedFiles: ["file-010"],
  },
  {
    id: "inv-016",
    patientId: "68103",
    date: "2024-04-03",
    type: "cardiology",
    source: "Cardiology",
    description: "48-hour Holter monitor — AFib rate control assessment",
    status: "completed",
    orderedBy: "Cardiology — Dr. R. Kapoor",
    notes:
      "Average HR 66 bpm. Rate controlled. No ventricular tachycardia. Occasional PACs noted. AFib burden 92% of recording.",
    statusHistory: [
      { status: "pending", date: "2024-03-20", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-03-28", updatedBy: "Cardiology Clinic" },
      { status: "completed", date: "2024-04-03", updatedBy: "Cardiology — Dr. R. Kapoor" },
    ],
    attachedFiles: ["file-011"],
  },
  {
    id: "inv-017",
    patientId: "68103",
    date: "2024-07-15",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "INR — supratherapeutic warfarin follow-up",
    status: "completed",
    orderedBy: "Chen, James",
    notes: "INR 3.8 at time of visit. Warfarin held 1 day, reduced to 4mg. Repeat INR in 1 week ordered.",
    statusHistory: [
      { status: "pending", date: "2024-07-15", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-07-15", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2024-07-15", updatedBy: "LifeLabs System" },
    ],
  },
  {
    id: "inv-018",
    patientId: "68103",
    date: "2024-09-05",
    type: "radiology",
    source: "Radiology",
    description: "Chest X-ray — evaluate for pulmonary congestion",
    status: "in-progress",
    orderedBy: "Chen, James",
    notes: "Ordered following patient report of increased dyspnea. Results pending radiology read.",
    statusHistory: [
      { status: "pending", date: "2024-09-05", updatedBy: "Chen, James" },
      { status: "in-progress", date: "2024-09-06", updatedBy: "Radiology Dept" },
    ],
  },

  // ─── Harold Whitmore (24884) ─────────────────────────────────────────────────
  {
    id: "inv-hw-001",
    patientId: "24884",
    date: "2010-09-15",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "Baseline fasting panel — CBC, CMP, HbA1c, lipid panel, TSH, urinalysis",
    status: "completed",
    orderedBy: "Park, Eleanor",
    notes: "HbA1c 6.1% (pre-diabetes). LDL 172 mg/dL, HDL 38, TG 210. Fasting glucose 118 mg/dL. TSH normal. UA unremarkable.",
    statusHistory: [
      { status: "pending", date: "2010-09-15", updatedBy: "Park, Eleanor" },
      { status: "in-progress", date: "2010-09-16", updatedBy: "LifeLabs System" },
      { status: "completed", date: "2010-09-20", updatedBy: "LifeLabs System" },
    ],
    attachedFiles: ["file-hwpdf-02"],
  },
  {
    id: "inv-hw-002",
    patientId: "24884",
    date: "2010-09-15",
    type: "cardiology",
    source: "Cardiology",
    description: "12-lead ECG — baseline",
    status: "completed",
    orderedBy: "Park, Eleanor",
    notes: "Normal sinus rhythm, rate 82. No acute ST-T changes. No evidence of prior infarct.",
    statusHistory: [
      { status: "pending", date: "2010-09-15", updatedBy: "Park, Eleanor" },
      { status: "completed", date: "2010-09-15", updatedBy: "Park, Eleanor" },
    ],
    attachedFiles: ["file-hwpdf-01"],
  },
  {
    id: "inv-hw-003",
    patientId: "24884",
    date: "2010-10-13",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "Fasting HbA1c + lipid panel — 4-week follow-up",
    status: "completed",
    orderedBy: "Park, Eleanor",
    notes: "HbA1c 6.1% confirmed. Lipids reviewed — atorvastatin 20mg initiated.",
    statusHistory: [
      { status: "pending", date: "2010-10-13", updatedBy: "Park, Eleanor" },
      { status: "completed", date: "2010-10-15", updatedBy: "LifeLabs System" },
    ],
  },
  {
    id: "inv-hw-004",
    patientId: "24884",
    date: "2012-03-22",
    type: "referral",
    source: "Other",
    description: "Colonoscopy referral — colorectal cancer screening (age 67)",
    status: "completed",
    orderedBy: "Park, Eleanor",
    referringPhysician: "Park, Eleanor",
    notes: "Screening colonoscopy completed 2013-06-15. Two small benign adenomatous polyps removed. Repeat in 5 years.",
    statusHistory: [
      { status: "pending", date: "2012-03-22", updatedBy: "Park, Eleanor" },
      { status: "in-progress", date: "2012-04-10", updatedBy: "GI Associates" },
      { status: "completed", date: "2013-06-15", updatedBy: "GI Associates" },
    ],
    attachedFiles: ["file-hwpdf-31"],
  },
  {
    id: "inv-hw-005",
    patientId: "24884",
    date: "2014-11-10",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "HbA1c — glycemic reassessment",
    status: "completed",
    orderedBy: "Park, Eleanor",
    notes: "HbA1c 7.2% — crosses diagnostic threshold for type 2 diabetes mellitus. Metformin initiated.",
    statusHistory: [
      { status: "pending", date: "2014-11-10", updatedBy: "Park, Eleanor" },
      { status: "completed", date: "2014-11-12", updatedBy: "LifeLabs System" },
    ],
  },
  {
    id: "inv-hw-006",
    patientId: "24884",
    date: "2018-07-08",
    type: "referral",
    source: "Other",
    description: "Ophthalmology referral — diabetic retinopathy screening",
    status: "completed",
    orderedBy: "Park, Eleanor",
    referringPhysician: "Park, Eleanor",
    notes: "No diabetic retinopathy detected on dilated fundus exam. Annual screening recommended.",
    statusHistory: [
      { status: "pending", date: "2018-07-08", updatedBy: "Park, Eleanor" },
      { status: "in-progress", date: "2018-07-20", updatedBy: "Reception" },
      { status: "completed", date: "2018-08-14", updatedBy: "Ophthalmology Clinic" },
    ],
    attachedFiles: ["file-hwpdf-19"],
  },
  {
    id: "inv-hw-007",
    patientId: "24884",
    date: "2018-07-08",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "PSA, HbA1c, comprehensive metabolic panel",
    status: "completed",
    orderedBy: "Park, Eleanor",
    notes: "PSA 3.2 ng/mL (DRE normal — watchful waiting). HbA1c 7.0%. CMP within normal limits.",
    statusHistory: [
      { status: "pending", date: "2018-07-08", updatedBy: "Park, Eleanor" },
      { status: "completed", date: "2018-07-10", updatedBy: "LifeLabs System" },
    ],
  },
  {
    id: "inv-hw-008",
    patientId: "24884",
    date: "2022-04-19",
    type: "cardiology",
    source: "Cardiology",
    description: "Transthoracic echocardiogram — EF and LVH assessment",
    status: "completed",
    orderedBy: "Park, Eleanor",
    referringPhysician: "Park, Eleanor",
    notes: "EF 52% (preserved). Mild concentric LVH. No regional wall motion abnormality. No significant valvular disease.",
    statusHistory: [
      { status: "pending", date: "2022-04-19", updatedBy: "Park, Eleanor" },
      { status: "in-progress", date: "2022-04-22", updatedBy: "Cardiology Dept" },
      { status: "completed", date: "2022-04-25", updatedBy: "Cardiology Dept" },
    ],
    attachedFiles: ["file-hwpdf-16"],
  },
  {
    id: "inv-hw-009",
    patientId: "24884",
    date: "2022-04-19",
    type: "cardiology",
    source: "Cardiology",
    description: "24-hour Holter monitor — palpitation workup",
    status: "completed",
    orderedBy: "Park, Eleanor",
    referringPhysician: "Park, Eleanor",
    notes: "Sinus rhythm with occasional PACs (0.4% burden). No sustained arrhythmia, no significant pauses. Symptoms not correlated with significant ectopy.",
    statusHistory: [
      { status: "pending", date: "2022-04-19", updatedBy: "Park, Eleanor" },
      { status: "completed", date: "2022-04-23", updatedBy: "Cardiology Dept" },
    ],
    attachedFiles: ["file-hwpdf-16"],
  },
  {
    id: "inv-hw-010",
    patientId: "24884",
    date: "2026-03-08",
    type: "lab",
    source: "Lab (LifeLabs)",
    description: "HbA1c, CMP, fasting lipids, eGFR — annual review",
    status: "completed",
    orderedBy: "Park, Eleanor",
    notes: "HbA1c 7.4% (slightly above target). eGFR 66 mL/min/1.73m² (CKD stage 2, stable). LDL at target on atorvastatin 40mg.",
    statusHistory: [
      { status: "pending", date: "2026-03-08", updatedBy: "Park, Eleanor" },
      { status: "completed", date: "2026-03-10", updatedBy: "LifeLabs System" },
    ],
  },
];

export function getInvestigationsByPatientId(patientId: string): Investigation[] {
  return investigations.filter((i) => i.patientId === patientId);
}

export function getInvestigationById(id: string): Investigation | undefined {
  return investigations.find((i) => i.id === id);
}
