// AUTO-GENERATED by scripts/gen-whitmore-records.mjs � do not edit by hand.
// Sources the real Whitmore medical-record PDFs served from public/records/whitmore.
import type { Encounter, FileRecord } from "@/lib/types";

export const whitmoreFiles: FileRecord[] = [
  {
    "id": "file-hwpdf-01",
    "patientId": "24884",
    "name": "01_2010-09-15_establishing-care-annual-health-maintenanc.pdf",
    "type": "pdf",
    "uploadedAt": "2010-09-15T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 7,
    "url": "/records/whitmore/01_2010-09-15_establishing-care-annual-health-maintenanc.pdf"
  },
  {
    "id": "file-hwpdf-02",
    "patientId": "24884",
    "name": "02_2010-10-13_fasting-metabolic-lipid-glycemic-panel-res.pdf",
    "type": "pdf",
    "uploadedAt": "2010-10-13T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 6,
    "url": "/records/whitmore/02_2010-10-13_fasting-metabolic-lipid-glycemic-panel-res.pdf"
  },
  {
    "id": "file-hwpdf-03",
    "patientId": "24884",
    "name": "03_2010-11-09_review-of-labs-new-diagnoses-t2dm-dyslipid.pdf",
    "type": "pdf",
    "uploadedAt": "2010-11-09T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/03_2010-11-09_review-of-labs-new-diagnoses-t2dm-dyslipid.pdf"
  },
  {
    "id": "file-hwpdf-04",
    "patientId": "24884",
    "name": "04_2011-10-18_evaluation-of-exertional-chest-discomfort.pdf",
    "type": "pdf",
    "uploadedAt": "2011-10-18T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/04_2011-10-18_evaluation-of-exertional-chest-discomfort.pdf"
  },
  {
    "id": "file-hwpdf-05",
    "patientId": "24884",
    "name": "05_2012-02-14_coronary-angiography-with-drug-eluting-ste.pdf",
    "type": "pdf",
    "uploadedAt": "2012-02-14T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/05_2012-02-14_coronary-angiography-with-drug-eluting-ste.pdf"
  },
  {
    "id": "file-hwpdf-06",
    "patientId": "24884",
    "name": "06_2012-03-20_post-pci-review-5-weeks.pdf",
    "type": "pdf",
    "uploadedAt": "2012-03-20T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/06_2012-03-20_post-pci-review-5-weeks.pdf"
  },
  {
    "id": "file-hwpdf-07",
    "patientId": "24884",
    "name": "07_2013-07-08_health-maintenance-elevated-screening-psa-.pdf",
    "type": "pdf",
    "uploadedAt": "2013-07-08T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/07_2013-07-08_health-maintenance-elevated-screening-psa-.pdf"
  },
  {
    "id": "file-hwpdf-08",
    "patientId": "24884",
    "name": "08_2013-09-02_transrectal-ultrasound-guided-12-core-pros.pdf",
    "type": "pdf",
    "uploadedAt": "2013-09-02T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/08_2013-09-02_transrectal-ultrasound-guided-12-core-pros.pdf"
  },
  {
    "id": "file-hwpdf-09",
    "patientId": "24884",
    "name": "09_2013-09-09_prostate-12-core-needle-biopsy-specimen-of.pdf",
    "type": "pdf",
    "uploadedAt": "2013-09-09T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 3,
    "url": "/records/whitmore/09_2013-09-09_prostate-12-core-needle-biopsy-specimen-of.pdf"
  },
  {
    "id": "file-hwpdf-10",
    "patientId": "24884",
    "name": "10_2013-09-30_newly-diagnosed-prostate-adenocarcinoma-st.pdf",
    "type": "pdf",
    "uploadedAt": "2013-09-30T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/10_2013-09-30_newly-diagnosed-prostate-adenocarcinoma-st.pdf"
  },
  {
    "id": "file-hwpdf-11",
    "patientId": "24884",
    "name": "11_2014-01-17_completion-of-definitive-prostate-imrt.pdf",
    "type": "pdf",
    "uploadedAt": "2014-01-17T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/11_2014-01-17_completion-of-definitive-prostate-imrt.pdf"
  },
  {
    "id": "file-hwpdf-12",
    "patientId": "24884",
    "name": "12_2014-09-25_post-radiotherapy-psa-surveillance-approac.pdf",
    "type": "pdf",
    "uploadedAt": "2014-09-25T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/12_2014-09-25_post-radiotherapy-psa-surveillance-approac.pdf"
  },
  {
    "id": "file-hwpdf-13",
    "patientId": "24884",
    "name": "13_2015-03-14_comprehensive-chronic-disease-review-age-7.pdf",
    "type": "pdf",
    "uploadedAt": "2015-03-14T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 7,
    "url": "/records/whitmore/13_2015-03-14_comprehensive-chronic-disease-review-age-7.pdf"
  },
  {
    "id": "file-hwpdf-14",
    "patientId": "24884",
    "name": "14_2015-04-18_psa-surveillance-result-of-march-2015-orde.pdf",
    "type": "pdf",
    "uploadedAt": "2015-04-18T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/14_2015-04-18_psa-surveillance-result-of-march-2015-orde.pdf"
  },
  {
    "id": "file-hwpdf-15",
    "patientId": "24884",
    "name": "15_2016-06-22_palpitations-dyspnea-new-atrial-fibrillati.pdf",
    "type": "pdf",
    "uploadedAt": "2016-06-22T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 6,
    "url": "/records/whitmore/15_2016-06-22_palpitations-dyspnea-new-atrial-fibrillati.pdf"
  },
  {
    "id": "file-hwpdf-16",
    "patientId": "24884",
    "name": "16_2016-07-07_atrial-fibrillation-management-echocardiog.pdf",
    "type": "pdf",
    "uploadedAt": "2016-07-07T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/16_2016-07-07_atrial-fibrillation-management-echocardiog.pdf"
  },
  {
    "id": "file-hwpdf-17",
    "patientId": "24884",
    "name": "17_2017-03-09_diabetes-intensification-newly-recognized-.pdf",
    "type": "pdf",
    "uploadedAt": "2017-03-09T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/17_2017-03-09_diabetes-intensification-newly-recognized-.pdf"
  },
  {
    "id": "file-hwpdf-18",
    "patientId": "24884",
    "name": "18_2017-04-20_type-2-diabetes-multifactorial-optimizatio.pdf",
    "type": "pdf",
    "uploadedAt": "2017-04-20T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/18_2017-04-20_type-2-diabetes-multifactorial-optimizatio.pdf"
  },
  {
    "id": "file-hwpdf-19",
    "patientId": "24884",
    "name": "19_2017-09-05_mild-non-proliferative-diabetic-retinopath.pdf",
    "type": "pdf",
    "uploadedAt": "2017-09-05T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 3,
    "url": "/records/whitmore/19_2017-09-05_mild-non-proliferative-diabetic-retinopath.pdf"
  },
  {
    "id": "file-hwpdf-20",
    "patientId": "24884",
    "name": "20_2017-10-19_bilateral-knee-radiographs-osteoarthritis.pdf",
    "type": "pdf",
    "uploadedAt": "2017-10-19T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 3,
    "url": "/records/whitmore/20_2017-10-19_bilateral-knee-radiographs-osteoarthritis.pdf"
  },
  {
    "id": "file-hwpdf-21",
    "patientId": "24884",
    "name": "21_2018-03-11_acute-decompensated-heart-failure-new-hfre.pdf",
    "type": "pdf",
    "uploadedAt": "2018-03-11T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 6,
    "url": "/records/whitmore/21_2018-03-11_acute-decompensated-heart-failure-new-hfre.pdf"
  },
  {
    "id": "file-hwpdf-22",
    "patientId": "24884",
    "name": "22_2018-03-17_acute-decompensated-heart-failure-hfref-ef.pdf",
    "type": "pdf",
    "uploadedAt": "2018-03-17T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/22_2018-03-17_acute-decompensated-heart-failure-hfref-ef.pdf"
  },
  {
    "id": "file-hwpdf-23",
    "patientId": "24884",
    "name": "23_2019-02-14_rising-psa-evaluation-for-biochemical-recu.pdf",
    "type": "pdf",
    "uploadedAt": "2019-02-14T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/23_2019-02-14_rising-psa-evaluation-for-biochemical-recu.pdf"
  },
  {
    "id": "file-hwpdf-24",
    "patientId": "24884",
    "name": "24_2019-03-08_psma-pet-ct-and-multiparametric-prostate-m.pdf",
    "type": "pdf",
    "uploadedAt": "2019-03-08T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 3,
    "url": "/records/whitmore/24_2019-03-08_psma-pet-ct-and-multiparametric-prostate-m.pdf"
  },
  {
    "id": "file-hwpdf-25",
    "patientId": "24884",
    "name": "25_2019-07-26_chronic-dyspnea-cough-copd-diagnosis.pdf",
    "type": "pdf",
    "uploadedAt": "2019-07-26T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/25_2019-07-26_chronic-dyspnea-cough-copd-diagnosis.pdf"
  },
  {
    "id": "file-hwpdf-26",
    "patientId": "24884",
    "name": "26_2020-04-19_covid-19-pneumonia-with-hypoxemic-respirat.pdf",
    "type": "pdf",
    "uploadedAt": "2020-04-19T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/26_2020-04-19_covid-19-pneumonia-with-hypoxemic-respirat.pdf"
  },
  {
    "id": "file-hwpdf-27",
    "patientId": "24884",
    "name": "27_2020-09-15_right-total-knee-arthroplasty.pdf",
    "type": "pdf",
    "uploadedAt": "2020-09-15T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/27_2020-09-15_right-total-knee-arthroplasty.pdf"
  },
  {
    "id": "file-hwpdf-28",
    "patientId": "24884",
    "name": "28_2020-10-14_post-right-total-knee-arthroplasty-4-weeks.pdf",
    "type": "pdf",
    "uploadedAt": "2020-10-14T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 3,
    "url": "/records/whitmore/28_2020-10-14_post-right-total-knee-arthroplasty-4-weeks.pdf"
  },
  {
    "id": "file-hwpdf-29",
    "patientId": "24884",
    "name": "29_2021-05-03_transient-right-arm-weakness-slurred-speec.pdf",
    "type": "pdf",
    "uploadedAt": "2021-05-03T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/29_2021-05-03_transient-right-arm-weakness-slurred-speec.pdf"
  },
  {
    "id": "file-hwpdf-30",
    "patientId": "24884",
    "name": "30_2021-06-10_post-tia-secondary-prevention-carotid-dupl.pdf",
    "type": "pdf",
    "uploadedAt": "2021-06-10T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/30_2021-06-10_post-tia-secondary-prevention-carotid-dupl.pdf"
  },
  {
    "id": "file-hwpdf-31",
    "patientId": "24884",
    "name": "31_2022-02-28_colonoscopy-egd-for-iron-deficiency-anemia.pdf",
    "type": "pdf",
    "uploadedAt": "2022-02-28T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/31_2022-02-28_colonoscopy-egd-for-iron-deficiency-anemia.pdf"
  },
  {
    "id": "file-hwpdf-32",
    "patientId": "24884",
    "name": "32_2022-03-05_colon-polyps-polypectomy-specimens-of-02-2.pdf",
    "type": "pdf",
    "uploadedAt": "2022-03-05T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 3,
    "url": "/records/whitmore/32_2022-03-05_colon-polyps-polypectomy-specimens-of-02-2.pdf"
  },
  {
    "id": "file-hwpdf-33",
    "patientId": "24884",
    "name": "33_2023-01-17_mechanical-fall-with-left-distal-radius-fr.pdf",
    "type": "pdf",
    "uploadedAt": "2023-01-17T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/33_2023-01-17_mechanical-fall-with-left-distal-radius-fr.pdf"
  },
  {
    "id": "file-hwpdf-34",
    "patientId": "24884",
    "name": "34_2023-02-14_osteoporosis-after-fragility-fracture-dexa.pdf",
    "type": "pdf",
    "uploadedAt": "2023-02-14T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/34_2023-02-14_osteoporosis-after-fragility-fracture-dexa.pdf"
  },
  {
    "id": "file-hwpdf-35",
    "patientId": "24884",
    "name": "35_2023-06-08_phacoemulsification-with-intraocular-lens-.pdf",
    "type": "pdf",
    "uploadedAt": "2023-06-08T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/35_2023-06-08_phacoemulsification-with-intraocular-lens-.pdf"
  },
  {
    "id": "file-hwpdf-36",
    "patientId": "24884",
    "name": "36_2024-03-07_progressive-hfref-ef-30-icd-evaluation-ech.pdf",
    "type": "pdf",
    "uploadedAt": "2024-03-07T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 7,
    "url": "/records/whitmore/36_2024-03-07_progressive-hfref-ef-30-icd-evaluation-ech.pdf"
  },
  {
    "id": "file-hwpdf-37",
    "patientId": "24884",
    "name": "37_2024-07-09_ckd-stage-g3b-g4-diabetic-cardiorenal-dise.pdf",
    "type": "pdf",
    "uploadedAt": "2024-07-09T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 5,
    "url": "/records/whitmore/37_2024-07-09_ckd-stage-g3b-g4-diabetic-cardiorenal-dise.pdf"
  },
  {
    "id": "file-hwpdf-38",
    "patientId": "24884",
    "name": "38_2024-10-15_prostate-cancer-10-year-survivorship-surve.pdf",
    "type": "pdf",
    "uploadedAt": "2024-10-15T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 4,
    "url": "/records/whitmore/38_2024-10-15_prostate-cancer-10-year-survivorship-surve.pdf"
  },
  {
    "id": "file-hwpdf-39",
    "patientId": "24884",
    "name": "39_2025-02-10_annual-multimorbidity-review-polypharmacy-.pdf",
    "type": "pdf",
    "uploadedAt": "2025-02-10T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 8,
    "url": "/records/whitmore/39_2025-02-10_annual-multimorbidity-review-polypharmacy-.pdf"
  },
  {
    "id": "file-hwpdf-40",
    "patientId": "24884",
    "name": "40_2025-05-06_heart-failure-exacerbation-with-atrial-fib.pdf",
    "type": "pdf",
    "uploadedAt": "2025-05-06T09:00:00",
    "uploadedBy": "Riverside Family Health Clinic",
    "sizeKb": 7,
    "url": "/records/whitmore/40_2025-05-06_heart-failure-exacerbation-with-atrial-fib.pdf"
  }
];

export const whitmoreEncounters: Encounter[] = [
  {
    "id": "enc-hwpdf-01",
    "patientId": "24884",
    "date": "2010-09-15",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Establishing care annual health maintenanc",
    "summary": "Establishing care annual health maintenanc. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-01"
    ]
  },
  {
    "id": "enc-hwpdf-02",
    "patientId": "24884",
    "date": "2010-10-13",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Fasting metabolic lipid glycemic panel res",
    "summary": "Fasting metabolic lipid glycemic panel res. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-02"
    ]
  },
  {
    "id": "enc-hwpdf-03",
    "patientId": "24884",
    "date": "2010-11-09",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Review of labs new diagnoses t2dm dyslipid",
    "summary": "Review of labs new diagnoses t2dm dyslipid. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-03"
    ]
  },
  {
    "id": "enc-hwpdf-04",
    "patientId": "24884",
    "date": "2011-10-18",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Evaluation of exertional chest discomfort",
    "summary": "Evaluation of exertional chest discomfort. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-04"
    ]
  },
  {
    "id": "enc-hwpdf-05",
    "patientId": "24884",
    "date": "2012-02-14",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Coronary angiography with drug eluting ste",
    "summary": "Coronary angiography with drug eluting ste. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-05"
    ]
  },
  {
    "id": "enc-hwpdf-06",
    "patientId": "24884",
    "date": "2012-03-20",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Post pci review 5 weeks",
    "summary": "Post pci review 5 weeks. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-06"
    ]
  },
  {
    "id": "enc-hwpdf-07",
    "patientId": "24884",
    "date": "2013-07-08",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Health maintenance elevated screening psa",
    "summary": "Health maintenance elevated screening psa. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-07"
    ]
  },
  {
    "id": "enc-hwpdf-08",
    "patientId": "24884",
    "date": "2013-09-02",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Transrectal ultrasound guided 12 core pros",
    "summary": "Transrectal ultrasound guided 12 core pros. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-08"
    ]
  },
  {
    "id": "enc-hwpdf-09",
    "patientId": "24884",
    "date": "2013-09-09",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Prostate 12 core needle biopsy specimen of",
    "summary": "Prostate 12 core needle biopsy specimen of. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-09"
    ]
  },
  {
    "id": "enc-hwpdf-10",
    "patientId": "24884",
    "date": "2013-09-30",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Newly diagnosed prostate adenocarcinoma st",
    "summary": "Newly diagnosed prostate adenocarcinoma st. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-10"
    ]
  },
  {
    "id": "enc-hwpdf-11",
    "patientId": "24884",
    "date": "2014-01-17",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Completion of definitive prostate imrt",
    "summary": "Completion of definitive prostate imrt. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-11"
    ]
  },
  {
    "id": "enc-hwpdf-12",
    "patientId": "24884",
    "date": "2014-09-25",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Post radiotherapy psa surveillance approac",
    "summary": "Post radiotherapy psa surveillance approac. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-12"
    ]
  },
  {
    "id": "enc-hwpdf-13",
    "patientId": "24884",
    "date": "2015-03-14",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Comprehensive chronic disease review age 7",
    "summary": "Comprehensive chronic disease review age 7. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-13"
    ]
  },
  {
    "id": "enc-hwpdf-14",
    "patientId": "24884",
    "date": "2015-04-18",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Psa surveillance result of march 2015 orde",
    "summary": "Psa surveillance result of march 2015 orde. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-14"
    ]
  },
  {
    "id": "enc-hwpdf-15",
    "patientId": "24884",
    "date": "2016-06-22",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Palpitations dyspnea new atrial fibrillati",
    "summary": "Palpitations dyspnea new atrial fibrillati. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-15"
    ]
  },
  {
    "id": "enc-hwpdf-16",
    "patientId": "24884",
    "date": "2016-07-07",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Atrial fibrillation management echocardiog",
    "summary": "Atrial fibrillation management echocardiog. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-16"
    ]
  },
  {
    "id": "enc-hwpdf-17",
    "patientId": "24884",
    "date": "2017-03-09",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Diabetes intensification newly recognized",
    "summary": "Diabetes intensification newly recognized. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-17"
    ]
  },
  {
    "id": "enc-hwpdf-18",
    "patientId": "24884",
    "date": "2017-04-20",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Type 2 diabetes multifactorial optimizatio",
    "summary": "Type 2 diabetes multifactorial optimizatio. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-18"
    ]
  },
  {
    "id": "enc-hwpdf-19",
    "patientId": "24884",
    "date": "2017-09-05",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Mild non proliferative diabetic retinopath",
    "summary": "Mild non proliferative diabetic retinopath. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-19"
    ]
  },
  {
    "id": "enc-hwpdf-20",
    "patientId": "24884",
    "date": "2017-10-19",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Bilateral knee radiographs osteoarthritis",
    "summary": "Bilateral knee radiographs osteoarthritis. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-20"
    ]
  },
  {
    "id": "enc-hwpdf-21",
    "patientId": "24884",
    "date": "2018-03-11",
    "type": "emergency",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Acute decompensated heart failure new hfre",
    "summary": "Acute decompensated heart failure new hfre. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-21"
    ]
  },
  {
    "id": "enc-hwpdf-22",
    "patientId": "24884",
    "date": "2018-03-17",
    "type": "emergency",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Acute decompensated heart failure hfref ef",
    "summary": "Acute decompensated heart failure hfref ef. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-22"
    ]
  },
  {
    "id": "enc-hwpdf-23",
    "patientId": "24884",
    "date": "2019-02-14",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Rising psa evaluation for biochemical recu",
    "summary": "Rising psa evaluation for biochemical recu. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-23"
    ]
  },
  {
    "id": "enc-hwpdf-24",
    "patientId": "24884",
    "date": "2019-03-08",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Psma pet ct and multiparametric prostate m",
    "summary": "Psma pet ct and multiparametric prostate m. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-24"
    ]
  },
  {
    "id": "enc-hwpdf-25",
    "patientId": "24884",
    "date": "2019-07-26",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Chronic dyspnea cough copd diagnosis",
    "summary": "Chronic dyspnea cough copd diagnosis. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-25"
    ]
  },
  {
    "id": "enc-hwpdf-26",
    "patientId": "24884",
    "date": "2020-04-19",
    "type": "emergency",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Covid 19 pneumonia with hypoxemic respirat",
    "summary": "Covid 19 pneumonia with hypoxemic respirat. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-26"
    ]
  },
  {
    "id": "enc-hwpdf-27",
    "patientId": "24884",
    "date": "2020-09-15",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Right total knee arthroplasty",
    "summary": "Right total knee arthroplasty. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-27"
    ]
  },
  {
    "id": "enc-hwpdf-28",
    "patientId": "24884",
    "date": "2020-10-14",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Post right total knee arthroplasty 4 weeks",
    "summary": "Post right total knee arthroplasty 4 weeks. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-28"
    ]
  },
  {
    "id": "enc-hwpdf-29",
    "patientId": "24884",
    "date": "2021-05-03",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Transient right arm weakness slurred speec",
    "summary": "Transient right arm weakness slurred speec. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-29"
    ]
  },
  {
    "id": "enc-hwpdf-30",
    "patientId": "24884",
    "date": "2021-06-10",
    "type": "emergency",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Post tia secondary prevention carotid dupl",
    "summary": "Post tia secondary prevention carotid dupl. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-30"
    ]
  },
  {
    "id": "enc-hwpdf-31",
    "patientId": "24884",
    "date": "2022-02-28",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Colonoscopy egd for iron deficiency anemia",
    "summary": "Colonoscopy egd for iron deficiency anemia. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-31"
    ]
  },
  {
    "id": "enc-hwpdf-32",
    "patientId": "24884",
    "date": "2022-03-05",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Colon polyps polypectomy specimens of 02 2",
    "summary": "Colon polyps polypectomy specimens of 02 2. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-32"
    ]
  },
  {
    "id": "enc-hwpdf-33",
    "patientId": "24884",
    "date": "2023-01-17",
    "type": "emergency",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Mechanical fall with left distal radius fr",
    "summary": "Mechanical fall with left distal radius fr. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-33"
    ]
  },
  {
    "id": "enc-hwpdf-34",
    "patientId": "24884",
    "date": "2023-02-14",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Osteoporosis after fragility fracture dexa",
    "summary": "Osteoporosis after fragility fracture dexa. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-34"
    ]
  },
  {
    "id": "enc-hwpdf-35",
    "patientId": "24884",
    "date": "2023-06-08",
    "type": "specialist",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Phacoemulsification with intraocular lens",
    "summary": "Phacoemulsification with intraocular lens. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-35"
    ]
  },
  {
    "id": "enc-hwpdf-36",
    "patientId": "24884",
    "date": "2024-03-07",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Progressive hfref ef 30 icd evaluation ech",
    "summary": "Progressive hfref ef 30 icd evaluation ech. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-36"
    ]
  },
  {
    "id": "enc-hwpdf-37",
    "patientId": "24884",
    "date": "2024-07-09",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Ckd stage g3b g4 diabetic cardiorenal dise",
    "summary": "Ckd stage g3b g4 diabetic cardiorenal dise. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-37"
    ]
  },
  {
    "id": "enc-hwpdf-38",
    "patientId": "24884",
    "date": "2024-10-15",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Prostate cancer 10 year survivorship surve",
    "summary": "Prostate cancer 10 year survivorship surve. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-38"
    ]
  },
  {
    "id": "enc-hwpdf-39",
    "patientId": "24884",
    "date": "2025-02-10",
    "type": "office-visit",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Annual multimorbidity review polypharmacy",
    "summary": "Annual multimorbidity review polypharmacy. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-39"
    ]
  },
  {
    "id": "enc-hwpdf-40",
    "patientId": "24884",
    "date": "2025-05-06",
    "type": "emergency",
    "physician": "Park, Eleanor",
    "chiefComplaint": "Heart failure exacerbation with atrial fib",
    "summary": "Heart failure exacerbation with atrial fib. Open the attached document for the full clinical record.",
    "attachedDocuments": [
      "file-hwpdf-40"
    ]
  }
];
